[project]
name = "streamlit-app"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "db-dtypes>=1.4.3",
    "google-cloud-bigquery>=3.33.0",
    "polars>=1.30.0",
    "streamlit>=1.45.1",
]
